import { StyleSheet } from 'react-native';

export const dashboardScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#800000',
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoIcon: {
    fontSize: 20,
    color: '#FFFFFF',
  },
  logoText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  realtimeIndicator: {
    marginLeft: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: 'rgba(96, 255, 132, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#60FF84',
  },
  realtimeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#60FF84',
  },
  logoImage: {
    width: 32,
    height: 32,
  },
  profileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  profileIcon: {
    fontSize: 18,
    color: '#FFFFFF',
  },
  attendantText: {
    fontSize: 14,
    color: '#FFFFFF',
    marginRight: 8,
  },
  profilePicture: {
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  profileInitials: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  profileImage: {
    borderRadius: 12,
  },
  iconButton: {
    padding: 8,
    marginLeft: 8,
  },
  iconText: {
    fontSize: 18,
    color: '#FFFFFF',
  },
  headerIcon: {
    width: 20,
    height: 20,
  },
  controlIcon: {
    width: 16,
    height: 16,
  },
  filterIcon: {
    width: 16,
    height: 16,
  },
  vehicleTypeIcon: {
    width: 40,
    height: 40,
  },
  content: {
    flex: 1,
  },
  sectionContainer: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  campusTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#800000',
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 10,
  },
  vehicleTypesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  vehicleTypeCard: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 6,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    opacity: 0.9,
  },
  vehicleIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
  vehicleTypeName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#64748B',
    marginBottom: 12,
    textAlign: 'center',
  },
  capacityInfo: {
    alignItems: 'center',
  },
  capacityText: {
    fontSize: 11,
    color: '#94A3B8',
    marginBottom: 1,
    fontWeight: '400',
  },
  parkingSlotsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  floorText: {
    fontSize: 14,
    color: '#666666',
    marginTop: 4,
  },
  controlsContainer: {
    alignItems: 'flex-end',
  },
  viewModeControls: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  vehicleTypeFilters: {
    flexDirection: 'row',
  },
  controlButton: {
    padding: 8,
    marginLeft: 4,
    borderRadius: 6,
    backgroundColor: '#F0F0F0',
  }, 
  activeControl: {
    backgroundColor: '#800000',
  },
  filterButton: {
    padding: 8,
    marginLeft: 4,
    borderRadius: 6,
    backgroundColor: '#F0F0F0',
  },
  activeFilter: {
    backgroundColor: '#800000',
  },
  parkingSlotsContainer: {
    marginTop: 10,
  },
  section: {
    marginBottom: 2,
  },
  slotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    paddingHorizontal: 0,
    gap: 8,
  },
  slotsList: {
    flexDirection: 'column',
    gap: 8,
  },
  parkingSlot: {
    width: 102,
    height: 131,
    borderRadius: 6,
    padding: 6,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  emptySlot: {
    width: 102,
    height: 131,
    // Invisible placeholder to maintain grid alignment
  },
  parkingSlotList: {
    width: '100%',
    minHeight: 70,
    borderRadius: 6,
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  slotId: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#383838',
    textAlign: 'center',
  },
  slotVehicleType: {
    fontSize: 10,
    color: '#383838',
    textAlign: 'center',
    marginTop: 0,
  },
  slotStatus: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#383838',
    textAlign: 'center',
    marginTop: 0,
  },
  slotIcon: {
    marginTop: 1,
  },
  // List view styles
  slotMainInfoList: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flex: 1,
  },
  slotIdList: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#383838',
    minWidth: 40,
  },
  slotVehicleTypeList: {
    fontSize: 12,
    color: '#383838',
    minWidth: 60,
  },
  slotDetailsList: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  slotStatusList: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#383838',
    minWidth: 60,
  },
  occupantInfoList: {
    fontSize: 11,
    color: '#383838',
    minWidth: 80,
  },
  plateInfoList: {
    fontSize: 10,
    color: '#383838',
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    minWidth: 60,
  },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#800000',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    zIndex: 1000,
  },
  fabIcon: {
    fontSize: 40,
    color: '#FFFFFF',
  },
  statusLegend: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  legendTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
    marginRight: 12,
  },
  legendItems: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-around',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  legendColor: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginRight: 8,
  },
  legendText: {
    fontSize: 14,
    color: '#666666',
  },
  // Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  filterSection: {
    padding: 20,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
  },
  filterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 15,
  },
  dropdownContainer: {
    flex: 1,
  },
  filterLabel: {
    fontSize: 14,
    color: '#333333',
    marginBottom: 8,
    fontWeight: '500',
  },
  dropdown: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
  },
  dropdownText: {
    fontSize: 14,
    color: '#333333',
  },
  dropdownArrow: {
    fontSize: 12,
    color: '#666666',
  },
  searchContainer: {
    flex: 1,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    backgroundColor: '#FFFFFF',
    color: '#333333',
  },
  tableContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    margin: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  tableContent: {
    flex: 1,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#800000',
    paddingVertical: 16,
    paddingHorizontal: 12,
  },
  tableHeaderCell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  tableHeaderText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginRight: 4,
  },
  sortIconContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    marginLeft: 4,
  },
  sortIcon: {
    marginVertical: 1,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: '#E5E5E5',
    paddingVertical: 16,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
  },
  tableCell: {
    flex: 1,
    fontSize: 13,
    color: '#333333',
    textAlign: 'center',
    paddingHorizontal: 8,
    fontWeight: '500',
  },
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#8A0000',
    marginTop: 10,
  },
  emptyContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: '#666666',
    marginBottom: 5,
  },
  emptySubtext: {
    fontSize: 14,
    color: '#999999',
  },
  // Settings Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    width: '100%',
    height: '85%',
    maxHeight: '90%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    backgroundColor: '#800000',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#800000',
  },
  settingsContent: {
    flex: 1,
    padding: 20,
  },
  settingsSection: {
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    padding: 16,
    backgroundColor: '#F8F9FA',
  },
  changePasswordSection: {
    marginBottom: 20,
  },
  settingsSectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#800000',
    marginBottom: 8,
  },
  sectionDescription: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 16,
    lineHeight: 20,
  },
  checkboxRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  checkboxLabel: {
    fontSize: 16,
    color: '#333333',
    flex: 1,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: '#800000',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  checkboxChecked: {
    backgroundColor: '#800000',
  },
  checkmark: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  accountInfoGrid: {
    marginBottom: 16,
  },
  accountInfoItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  accountLabel: {
    fontSize: 14,
    color: '#333333',
    fontWeight: '500',
  },
  accountValue: {
    fontSize: 14,
    color: '#666666',
    flex: 1,
    textAlign: 'right',
  },
  adminNote: {
    fontSize: 12,
    color: '#666666',
    fontStyle: 'italic',
    marginBottom: 8,
  },
  adminContact: {
    fontSize: 14,
    color: '#333333',
    marginBottom: 4,
  },
  adminButton: {
    backgroundColor: '#800000',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 6,
    alignItems: 'center',
    marginTop: 8,
    alignSelf: 'stretch',
  },
  adminButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  logoutButton: {
    backgroundColor: '#800000',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 6,
    alignItems: 'center',
    marginTop: 3,
    marginBottom: 30,
    alignSelf: 'stretch',
  },
  logoutButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  // Slot Details Modal Styles
  slotDetailsModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  slotDetailsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#800000',
    textAlign: 'center',
    marginBottom: 20,
  },
  slotDetailsContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  slotDetailsColumn: {
    flex: 1,
    paddingHorizontal: 8,
  },
  slotDetailRow: {
    marginBottom: 12,
  },
  slotDetailLabel: {
    fontSize: 14,
    color: '#333333',
    marginBottom: 4,
  },
  slotDetailValue: {
    fontSize: 14,
    color: '#666666',
    fontWeight: '500',
  },
  goBackButton: {
    backgroundColor: '#800000',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
  },
  goBackButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  errorText: {
    fontSize: 16,
    color: '#FF6C6C',
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 20,
  },
  // Motorcycle Capacity Sections Styles
  capacitySectionsContainer: {
    flexDirection: 'column',
    gap: 15,
  },
  capacitySectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderLeftWidth: 4,
    borderLeftColor: '#800000',
  },
  capacitySectionHeader: {
    marginBottom: 12,
  },
  capacitySectionTitle: {
    fontWeight: 'bold',
    color: '#333333',
  },
  capacitySectionSubtitle: {
    color: '#666666',
    marginTop: 2,
  },
  capacityStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  capacityStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  capacityStatNumber: {
    fontWeight: 'bold',
    color: '#333333',
  },
  capacityStatLabel: {
    color: '#666666',
    marginTop: 2,
  },
  parkedUsersPreview: {
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    padding: 10,
  },
  parkedUsersTitle: {
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 4,
  },
  parkedUserText: {
    color: '#666666',
    marginBottom: 2,
  },
  parkedUsersMore: {
    color: '#999999',
    fontStyle: 'italic',
  },
  noCapacitySections: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 20,
  },
  noCapacityText: {
    color: '#666666',
  },
  utilizationBar: {
    height: 6,
    backgroundColor: '#E0E0E0',
    borderRadius: 3,
    marginTop: 8,
    marginBottom: 8,
    overflow: 'hidden',
  },
  utilizationFill: {
    height: '100%',
    borderRadius: 3,
  },
  spotsGridContainer: {
    marginTop: 12,
  },
  showSpotsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#F0F8FF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#007AFF',
  },
  showSpotsButtonText: {
    color: '#007AFF',
    fontWeight: '600',
    marginRight: 4,
  },
  spotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginTop: 8,
    gap: 4,
  },
  spotItem: {
    width: 40,
    height: 40,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
    position: 'relative',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  spotNumber: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 10,
  },
  userBookedIndicator: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 1,
  },
  retryButton: {
    backgroundColor: '#800000',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 16,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  parkingSpotList: {
    width: '100%',
    minHeight: 70,
    borderRadius: 6,
    padding: 12,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  slotOccupantList: {
    fontSize: 12,
    color: '#383838',
    minWidth: 80,
  },
  slotPlateList: {
    fontSize: 10,
    color: '#383838',
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
});

export default dashboardScreenStyles;